project:
  type: website
  output-dir: docs

execute:
  freeze: auto  # re-render only when source changes
  eval: false

date-modified: last-modified

title-block-style: none

website:
  title: "Introduction to the cli"
    
  sidebar:
  - id: "Welcome page"
    style: "docked"
    search: true
    collapse: true

    contents:
      - text: "Welcome page"
        href: index.qmd

      - section: "Cli basics"
        contents:
          - source/installation.qmd
          - source/code_documentation.qmd
          - source/bash_intro.qmd
      
      - section: "Using an HPC"
        contents:
          - source/hpc_intro.qmd
          - source/hpc_howto.qmd

      - text: "An example notebook"
        href: source/example_doc.qmd


  page-navigation: true
  page-footer:  
    center: | 
      Copyright 2024, Nina Dombrowski,    
      Last modified: {{< meta date-modified >}} 

format:
  html:
    grid: 
      body-width: 1800px
    theme:
      light: lumen
      dark: cyborg
    toc: true
    toc-title: Contents
    toc-expand: 2
    link-external-newwindow: true

  pdf:
    documentclass: scrreprt
    pdf-engine: pdflatex
    geometry:
    #  - top=25mm
    #  - right=20mm
    #  - left=10mm
    #  - bottom=4mm
    #  - textwidth=4.5in
      - heightrounded      
    highlight-style: github
    pandoc_args: --listings
    colorlinks: true
    code-block-bg: D3D3D3  
    link-external-newwindow: true
    toc: true
    keep-tex: true
    include-in-header: 
       text: |
         \usepackage{fvextra}
         \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
    include-before-body:
      text: |
        \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
          showspaces = false,
          showtabs = false,
          breaksymbolleft={},
          breaklines
        }